class ClientOrder {
  int orderId;
  int clientId;
  int cityId;
  String city;
  int countyId;
  String county;
  DateTime date;
  String status;
  int languageId;
  String language;
  String languageCode;
  DateTime timeStart;
  DateTime timeEnd;
  double priceRangeStart;
  double priceRangeEnd;
  String placeName;
  String address;
  int activityId;
  String activity;
  double latitude;
  double longitude;
  String mode;
  double rate;
  int targetId;
  String target;
  ClientOrder({
    required this.orderId,
    required this.clientId,
    required this.cityId,
    required this.city,
    required this.countyId,
    required this.county,
    required this.date,
    required this.status,
    required this.languageId,
    required this.language,
    required this.languageCode,
    required this.timeStart,
    required this.timeEnd,
    required this.priceRangeStart,
    required this.priceRangeEnd,
    required this.placeName,
    required this.address,
    required this.activityId,
    required this.activity,
    required this.latitude,
    required this.longitude,
    required this.mode,
    required this.rate,
    required this.targetId,
    required this.target,
  });
}
